# Generated by Django 3.2.9 on 2021-11-30 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CandidateApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatelogin',
            name='ProfileAdded',
            field=models.CharField(default='name', max_length=100),
        ),
    ]
