# Generated by Django 3.2.9 on 2021-12-02 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CandidateApp', '0002_candidatelogin_profileadded'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidateprofile',
            name='Profile',
        ),
    ]
