# Generated by Django 3.2.9 on 2021-12-02 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectionPostion',
            fields=[
                ('Position', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('PostionTimeCreated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
