# Generated by Django 3.2.9 on 2021-12-02 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0002_electionpostion'),
    ]

    operations = [
        migrations.CreateModel(
            name='PositionBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CandidateUserId', models.CharField(max_length=100, unique=True)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.electionpostion')),
            ],
        ),
    ]
