# Generated by Django 3.2.9 on 2021-12-02 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0003_positionblock'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminApplicationForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=200)),
                ('gender', models.CharField(max_length=20)),
                ('StandPosition', models.CharField(max_length=200)),
            ],
        ),
    ]
