# Generated by Django 3.2.9 on 2021-12-04 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0004_adminapplicationform'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CandidateUserId', models.CharField(max_length=100)),
                ('StudentId', models.CharField(max_length=150)),
                ('Studentvotingtime', models.DateTimeField(auto_now=True)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.positionblock')),
            ],
        ),
    ]
