# Generated by Django 3.2.9 on 2021-11-27 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='AlternateNumber',
            field=models.CharField(default='Alternate Number', max_length=25),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='Phone',
            field=models.CharField(default='Add Number', max_length=20),
        ),
    ]
