# Generated by Django 3.2.9 on 2021-11-27 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0002_auto_20211127_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='Email',
            field=models.EmailField(default='User@example.com', max_length=100),
        ),
    ]
