# Generated by Django 3.2.9 on 2021-11-30 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0003_alter_userprofile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlogin',
            name='ProfileAdded',
            field=models.CharField(default='name', max_length=100),
        ),
    ]
