# Generated by Django 3.2.9 on 2021-12-02 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0005_alter_userlogin_profileadded'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='Profile',
        ),
    ]
