# Generated by Django 3.2.9 on 2021-11-30 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaffLogin',
            fields=[
                ('UserId', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('Password', models.CharField(max_length=100)),
                ('StaffActive', models.CharField(default='1', max_length=10)),
                ('AccountCreated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('UserId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Staff.stafflogin')),
                ('Name', models.CharField(default='Enter your Name', max_length=100)),
                ('Phone', models.CharField(default='Add Number', max_length=20)),
                ('AlternateNumber', models.CharField(default='Alternate Number', max_length=25)),
                ('Email', models.EmailField(default='User@example.com', max_length=100)),
                ('Gender', models.CharField(default='gender!', max_length=19)),
            ],
        ),
    ]
